controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - hip
      - shoulder
      - elbow
      - 3dprinted
      - wrist
  - name: fake_ee_gripper_controller
    type: $(arg execution_type)
    joints:
      - wrist
initial:  # Define initial robot poses.
  - group: arm
    pose: home